#!/usr/bin/env python3
"""Refresh local Netease playlist snapshots for Music Agent.

No LLM/chat/embedding API is called here.  It only uses the logged-in pyncm
session, updates runtime/playlists.json, refreshes playlist track cache, and
rebuilds the editable alias table.
"""
from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
import time
from pathlib import Path

ROOT = Path(os.environ.get('XIAOMI_MUSIC_ROOT', Path.home() / 'xiaomi-music')).expanduser()
CLOUD_SRC = ROOT / 'agents' / 'cloud-music-mcp' / 'src'
PLAYLISTS_FILE = ROOT / 'runtime' / 'playlists.json'
TRACK_CACHE_FILE = ROOT / 'runtime' / 'playlist_tracks_cache.json'
BACKUP_DIR = ROOT / 'runtime' / 'backups'

sys.path.insert(0, str(ROOT / 'scripts'))
try:
    from music_disable_rules import filter_playlists, filter_tracks, load_disable_rules
except Exception:
    def filter_playlists(playlists, rules=None): return list(playlists or [])
    def filter_tracks(tracks, rules=None): return list(tracks or [])
    def load_disable_rules(): return {}


def backup(path: Path) -> None:
    if not path.exists():
        return
    BACKUP_DIR.mkdir(parents=True, exist_ok=True)
    ts = time.strftime('%Y%m%d-%H%M%S')
    dst = BACKUP_DIR / f'{path.name}.{ts}.bak'
    dst.write_bytes(path.read_bytes())


def fetch_user_playlists():
    sys.path.insert(0, str(CLOUD_SRC))
    from cloud_music_mcp.auth import load_session
    from pyncm import apis
    ok, nickname = load_session()
    if not ok:
        raise RuntimeError('网易云 pyncm session 未登录；请先完成 cloud-music-mcp 登录')
    user_info = apis.login.GetCurrentLoginStatus()
    uid = user_info['profile']['userId']
    result = apis.user.GetUserPlaylists(uid)
    if result.get('code') != 200:
        raise RuntimeError(f'获取歌单列表失败: {result}')
    playlists = []
    for pl in result.get('playlist') or []:
        playlists.append({
            'id': str(pl.get('id')),
            'name': pl.get('name', ''),
            'count': int(pl.get('trackCount') or 0),
            'creator': (pl.get('creator') or {}).get('nickname', ''),
            'is_mine': (pl.get('creator') or {}).get('userId') == uid,
        })
    return nickname, playlists


def fetch_playlist_tracks(pid: str):
    sys.path.insert(0, str(CLOUD_SRC))
    from cloud_music_mcp.auth import load_session
    from pyncm import apis
    load_session()
    result = apis.playlist.GetPlaylistInfo(int(pid))
    if result.get('code') != 200 or not result.get('playlist'):
        raise RuntimeError(f'获取歌单曲目失败 {pid}: {str(result)[:300]}')
    tracks = []
    for t in result['playlist'].get('tracks') or []:
        artists = '/'.join([a.get('name', '') for a in t.get('ar', []) if a.get('name')])
        tracks.append({
            'id': str(t.get('id')),
            'name': t.get('name', ''),
            'artist': artists,
            'duration_ms': int(t.get('dt') or 0),
        })
    return result['playlist'].get('name', ''), tracks


def load_track_cache():
    if not TRACK_CACHE_FILE.exists():
        return {'updated_at': 0, 'playlists': {}}
    try:
        data = json.loads(TRACK_CACHE_FILE.read_text(encoding='utf-8'))
        return data if isinstance(data, dict) else {'updated_at': 0, 'playlists': {}}
    except Exception:
        return {'updated_at': 0, 'playlists': {}}


def save_json(path: Path, data) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--list-only', action='store_true', help='只同步歌单列表，不刷新曲目缓存')
    ap.add_argument('--missing-only', action='store_true', help='只给新增/缺失歌单拉取曲目；不刷新已有曲目')
    args = ap.parse_args()

    rules = load_disable_rules()
    nickname, raw_playlists = fetch_user_playlists()
    enabled_playlists = filter_playlists(raw_playlists, rules)
    enabled_ids = {str(p['id']) for p in enabled_playlists}

    backup(PLAYLISTS_FILE)
    save_json(PLAYLISTS_FILE, {
        'success': True,
        'updated_at': time.time(),
        'updated_at_text': time.strftime('%Y-%m-%d %H:%M:%S'),
        'account_hint': nickname,
        'note': 'Generated by scripts/sync_netease_playlists.sh. Disabled items are configured in runtime/music_disabled.json.',
        'playlists': raw_playlists,
    })

    cache = load_track_cache()
    old = cache.get('playlists') or {}
    new_cache = {pid: entry for pid, entry in old.items() if str(pid) in enabled_ids}
    refreshed = 0
    failed = []
    if not args.list_only:
        for pl in enabled_playlists:
            pid = str(pl['id'])
            if args.missing_only and pid in new_cache:
                continue
            try:
                name, tracks = fetch_playlist_tracks(pid)
                new_cache[pid] = {
                    'name': name or pl.get('name', ''),
                    'tracks': tracks,
                    'cached_at': time.time(),
                }
                refreshed += 1
                print(f'[sync] tracks {pl.get("name")} ({pid}) raw={len(tracks)} enabled={len(filter_tracks(tracks, rules))}')
            except Exception as e:
                failed.append({'id': pid, 'name': pl.get('name', ''), 'error': str(e)})
                print(f'[sync] WARN failed {pl.get("name")} ({pid}): {e}', file=sys.stderr)
    backup(TRACK_CACHE_FILE)
    save_json(TRACK_CACHE_FILE, {'updated_at': time.time(), 'playlists': new_cache})

    # Rebuild aliases from the newly synced playlist snapshot.  The builder also
    # respects runtime/music_disabled.json.
    subprocess.run([sys.executable, str(ROOT / 'scripts' / 'build_playlist_aliases.py')], check=True, cwd=str(ROOT))

    print(json.dumps({
        'ok': True,
        'account': nickname,
        'playlists_raw': len(raw_playlists),
        'playlists_enabled': len(enabled_playlists),
        'playlists_disabled': len(raw_playlists) - len(enabled_playlists),
        'track_playlists_refreshed': refreshed,
        'failed': failed,
        'files': {
            'playlists': str(PLAYLISTS_FILE),
            'track_cache': str(TRACK_CACHE_FILE),
            'disabled_rules': str(ROOT / 'runtime' / 'music_disabled.json'),
        },
    }, ensure_ascii=False, indent=2))


if __name__ == '__main__':
    main()
